[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
rapier2d = "0.26.1"  # For 2D physics
burn = { version = "0.17.1", features = ["ndarray"] }
rand = { version = "0.9" }

[profile.release]
debug = 1